version: 0.2

env:
  shell: bash
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building frontend application..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
